include: package:lint/analysis_options.yaml

linter:
  rules:
    avoid_print: false
    constant_identifier_names: false

analyzer:
  strong-mode:
    implicit-casts: false
  errors:
    missing_required_param: error
    missing_return: warning
    todo: ignore
    parameter_assignments: error
  exclude:
    - 'bin/cache/**'
    # the following two are relative to the stocks example and the flutter package respectively
    # see https://github.com/dart-lang/sdk/issues/28463
    - 'lib/i18n/messages_*.dart'
    - 'lib/src/http/**'
    - 'lib/domain/models/*.g.dart'
    - '/git_hooks.dart'
